# Generated by Django 4.2.16 on 2025-04-27 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_view_name', models.CharField(max_length=50, verbose_name='Название системной цели')),
            ],
            options={
                'verbose_name': 'Базовая цель',
                'verbose_name_plural': 'Базовые цели',
            },
        ),
        migrations.CreateModel(
            name='DefaultStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_description', models.CharField(max_length=100, verbose_name='Описание шага')),
            ],
            options={
                'verbose_name': 'Базовый шаг',
                'verbose_name_plural': 'Базовые шаги',
            },
        ),
        migrations.CreateModel(
            name='DefaultSubGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_goal_name', models.CharField(max_length=50, verbose_name='Название побочной цели')),
                ('main_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_subgoals', to='GoMap.defaultgoal')),
            ],
            options={
                'verbose_name': 'Базовая побочная цель',
                'verbose_name_plural': 'Базовые побочные цели',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='GeneralQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Общий вопрос',
                'verbose_name_plural': 'Общие вопросы',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=50, verbose_name='Название цели')),
                ('progress_goal', models.IntegerField(default=0)),
                ('default_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GoMap.defaultgoal', verbose_name='Базовая цель')),
            ],
            options={
                'verbose_name': 'Цель пользователя',
                'verbose_name_plural': 'Цели пользователей',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
            },
        ),
        migrations.CreateModel(
            name='UserGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_point', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_subgoal', models.IntegerField(default=0)),
                ('default_subgoal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GoMap.defaultsubgoal', verbose_name='Базовая побочная цель')),
                ('main_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_subgoals', to='GoMap.goal')),
            ],
            options={
                'verbose_name': 'Побочная цель пользователя',
                'verbose_name_plural': 'Побочные цели пользователей',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_description', models.CharField(max_length=100, verbose_name='Описание шага')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('default_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GoMap.defaultstep', verbose_name='Базовый шаг')),
                ('subgoal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='GoMap.subgoal')),
            ],
            options={
                'verbose_name': 'Шаг пользователя',
                'verbose_name_plural': 'Шаги пользователей',
            },
        ),
        migrations.CreateModel(
            name='Specific_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GoMap.specific_question')),
            ],
            options={
                'verbose_name': 'Спецфичный вопрос',
                'verbose_name_plural': 'Спецфичные вопросы',
            },
        ),
        migrations.CreateModel(
            name='Specific_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_answers', to='GoMap.specific_question')),
                ('points', models.ManyToManyField(related_name='specific_answers', to='GoMap.point')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='GoMap.specific_question')),
            ],
            options={
                'verbose_name': 'Спецфичный ответ',
                'verbose_name_plural': 'Спецфичные ответы',
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='subgoals',
            field=models.ManyToManyField(blank=True, related_name='goals', to='GoMap.subgoal'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='GeneralAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('points', models.ManyToManyField(related_name='general_answers', to='GoMap.point')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='GoMap.generalquestion')),
            ],
            options={
                'verbose_name': 'Общий ответ',
                'verbose_name_plural': 'Общие ответы',
            },
        ),
        migrations.AddField(
            model_name='defaultstep',
            name='subgoal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_steps', to='GoMap.defaultsubgoal'),
        ),
        migrations.AddField(
            model_name='defaultgoal',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_goals', to='GoMap.direction'),
        ),
        migrations.AddField(
            model_name='defaultgoal',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='default_goals', to='GoMap.point'),
        ),
    ]
