# Generated by Django 4.2.16 on 2025-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specific_question',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
    ]
