# Generated by Django 4.2.16 on 2025-05-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoMap', '0002_specific_question_is_first'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specific_answer',
            options={'verbose_name': 'Специфичный ответ', 'verbose_name_plural': 'Специфичные ответы'},
        ),
        migrations.AlterModelOptions(
            name='specific_question',
            options={'verbose_name': 'Специфичный вопрос', 'verbose_name_plural': 'Специфичные вопросы'},
        ),
        migrations.RemoveField(
            model_name='specific_answer',
            name='next_question',
        ),
        migrations.RemoveField(
            model_name='specific_question',
            name='is_first',
        ),
        migrations.RemoveField(
            model_name='specific_question',
            name='parent_question',
        ),
        migrations.AddField(
            model_name='specific_question',
            name='direction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specific_questions', to='GoMap.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='specific_answer',
            name='points',
            field=models.ManyToManyField(related_name='specific_answers', to='GoMap.point', verbose_name='Метки'),
        ),
        migrations.AlterField(
            model_name='specific_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='GoMap.specific_question', verbose_name='Специфичный вопрос'),
        ),
        migrations.AlterField(
            model_name='specific_answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='specific_question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст вопроса'),
        ),
    ]
