# Generated by Django 4.2.16 on 2025-05-02 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GoMap', '0003_alter_specific_answer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specific_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='GoMap.specific_question'),
        ),
    ]
