# Generated by Django 4.2.16 on 2025-05-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoMap', '0004_alter_specific_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultgoal',
            name='direction',
        ),
    ]
