# Generated by Django 4.2.16 on 2025-05-02 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GoMap', '0005_remove_defaultgoal_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoals',
            name='goals_point',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usergoals',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
