# Generated by Django 4.2.16 on 2025-05-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GoMap', '0006_alter_usergoals_goals_point_alter_usergoals_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='text',
            new_name='name',
        ),
    ]
