# Generated by Django 4.2.16 on 2025-05-02 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GoMap', '0007_rename_text_point_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='subgoal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subgoals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
